fix(renv): Update S4Arrays to match current Bioconductor versionERROR [error code 22]
- Change S4Arrays from v1.7.2 to v1.8.1 to match current Bioconductor
release 3.21 and R 4.5.
- Ensures that the version from the downloaded URL matches what is on
the `renv.lock` and avoid conflicts from a previous version not
available there anymore.

Fixes these issues:

Downloading matrixStats from CRAN ...         OK [file is up to date]
Downloading S4Arrays from Bioconductor 3.21 ... ERROR [error code 22]
Error: failed to retrieve package 'bioc::DelayedArray@0.34.1'